services:
  back:
    build: .
    container_name: back
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/quer_apostar?schema=public
    networks:
      - postgres-net
    depends_on:
      - postgres
      
  postgres:
    container_name: postgres
    image: postgres:alpine3.18
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-net
    # volumes:
    #   - postgres-volume:/var/lib//postgresql/data

networks:
  postgres-net:

# volumes:
#   postgres-volume: